language: python
python:
  - '3.3'
  - '3.4'
install:
  - pip install -e .
  - pip install pytest-cov pytest-pep8 coveralls
script:
  - sh util/test.sh
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Lucretiel
  password:
    secure: kLTVnrjyggnqaGnLAi5M02LDGIC/hfQmdFD+2onZVjRyj3EKYvZ/INz9NtIPgMo4ocixe59LPJI40nORm53ifPiKZs0HikRw7Z/ebzqDXsyShlP4alxd35jXglDV+dRF8yT86UxlLYaUWp5JYODcGKZuMpBGqxu6KD2apq1EILc=
  on:
    tags: true
  distributions: sdist bdist_wheel
