language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .
  - pip install coverage
# command to run tests, e.g. python setup.py test
script: sh -x util/test.sh
